services:
  request_parser:
    build:
      context: ./RequestParser
      dockerfile: Dockerfile
    container_name: request_parser
    env_file:
      - .env
    ports:
      - "5000:5000"

  target_freelance_bot:
    build:
      context: ./TargetFreelanceBot
      dockerfile: Dockerfile
    container_name: target_freelance_bot
    env_file:
      - .env.test
    depends_on:
      - request_parser

  smm_freelance_bot:
    build:
      context: ./SMMFreelanceBot
      dockerfile: Dockerfile
    container_name: smm_freelance_bot
    env_file:
      - .env
    depends_on:
      - request_parser