services:
  request_parser:
    build:
      context: ./RequestParser
      dockerfile: Dockerfile
    container_name: request_parser
    ports:
      - "5000:5000"

  target_freelance_bot:
    build:
      context: ./TargetFreelanceBot
      dockerfile: Dockerfile
    container_name: target_freelance_bot
    depends_on:
      - request_parser

  smm_freelance_bot:
    build:
      context: ./SMMFreelanceBot
      dockerfile: Dockerfile
    container_name: smm_freelance_bot
    depends_on:
      - request_parser