version: '3.8'

services:
  request_parser:
    build:
      context: ./RequestParser
      dockerfile: Dockerfile
    container_name: request_parser
    env_file:
      - .env.test
    ports:
      - "5000:5000"

  freelance_bot:
    build:
      context: ./FreelanceBot
      dockerfile: Dockerfile
    container_name: freelance_bot
    env_file:
      - .env.test
    depends_on:
      - request_parser