services:
  request_parser:
    build:
      context: ./RequestParser
      dockerfile: Dockerfile
    container_name: request_parser
    env_file:
      - ${WINJOB_ENV_FILE}
    ports:
      - "5000:5000"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  target_freelance_bot:
    build:
      context: ./TargetFreelanceBot
      dockerfile: Dockerfile
    container_name: target_freelance_bot
    env_file:
      - ${WINJOB_ENV_FILE}
    depends_on:
      - request_parser

  smm_freelance_bot:
    build:
      context: ./SMMFreelanceBot
      dockerfile: Dockerfile
    container_name: smm_freelance_bot
    env_file:
      - ${WINJOB_ENV_FILE}
    depends_on:
      - request_parser